name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the ocrmypdf Docker image
      run: |
       docker build . --tag ghcr.io/teserak/ocrmypdf:latest
       docker run ghcr.io/teserak/ocrmypdf:latest
       docker push ghcr.io/teserak/ocrmypdf:latest
